apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: hello-world
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: busybox:1.36
        command: ['sh', '-c', 'echo "Hello world from demo cluster!" && sleep 3600']
